site_name: OpenMovies Documentation

theme:
  name: readthedocs
  nav_style: dark

nav:
  - Home: index.md
  - About: about.md
  - Endpoints:
    - Movies: endpoints/movies.md
    - Directors: endpoints/directors.md
    - Categories: endpoints/categories.md
  - Release Notes:
    - V1.0: release-notes/v1.0.md